#!/bin/bash

if [[ $# -eq 0 ]]
then
	 ./client.out -h 127.0.0.1 -p 2000

elif [[ $# -ne 1 ]]
then
	echo "USAGE $0: script takes username as argument"
	exit -1
else
	 ./client.out -h 127.0.0.1 -u $1 -p 2000
fi


