#! /bin/bash

if [[ $# -ne 4 ]]
then
	echo "USAGE $0: takes two arguments:"
	echo "       > hostname"
	echo "       > username"
	exit -1
fi

echo "Run foreign $1 $2 $3 $4"
./client.out -h $1 -u $2 -p 2000 -t $3 -k $4

